sudo: required
services:
  - docker

brfore_install:
  - docker build -t vinovero/multi-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vinovero/multi-react-test npm run test -- --coverage

after_success:
  - docker build -t vinovero/multi-client ./client
  - docker build -t vinovero/multi-nginx ./nginx
  - docker build -t vinovero/multi-server ./server
  - docker build -t vinovero/multi-worker ./worker 
  #Log in the docker CLI
  - docker logout
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push vinovero/multi-client
  - docker push vinovero/multi-nginx
  - docker push vinovero/multi-server
  - docker push vinovero/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker-sample
  env: MultiDockerSample-env
  bucket_name: elasticbeanstalk-us-east-2-227641873353
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY    